### PR TITLE
chore: update stdlib from 0.44 to 0.48 and ranger to require >= 1.4.0

### LINKED ISSUE #41: Update stdlib usage
Hello!

The stdlib is undergoing a latest round of deprecations. There's a bunch of errors being emitted by this library, it would be fab to have them fixed!

Thank you,
Louis

### PR DESCRIPTION
**Pull request by dinkelspiel**
Closes #41

### CODE REVIEW

**Comment by GauBen** [comment]
Damn your timing is fabulous, I was just investigating a `error: Type mismatch` on `yielder.Yielder(Time)`

Hope it gets merged soon!

**Comment by kemo-1** [comment]
> Damn your timing is fabulous, I was just investigating a `error: Type mismatch` on `yielder.Yielder(Time)`
> 
> Hope it gets merged soon!

i fixed that 3 hours ago and it got merged at the same time it just needs the updated the package to be published to hex

**Comment by GauBen** [comment]
Thanks for your many contributions @kemo-1!

It probably needs this very PR for the CI to turn green https://github.com/massivefermion/birl/actions/runs/12388645351/job/34580106412 and a release by massivefermion afterwards

**Comment by richard-viney** [comment]
Would be good to update the `ranger` version in `gleam.toml` to be explicitly `>= 1.4.0` as that's the version that has the iterator updates.

**Comment by dinkelspiel** [comment]
> Would be good to update the `ranger` version in `gleam.toml` to be explicitly `>= 1.4.0` as that's the version that has the iterator updates.

resolved this comment

**Comment by massivefermion** [comment]
Thanks

**Pull request merged**
